<?php
if (!defined('ABSPATH') || !dsmart_analytics_allowed()) { return; }
$f = dsmart_analytics_filters($_GET);
if (is_wp_error($f)) {
    echo '<p role="alert">' . esc_html($f->get_error_message()) . '</p>';
    $f = dsmart_analytics_filters(array());
}
$r = dsmart_analytics_report($f);
$analytics_admin = is_admin();
$analytics_url = $analytics_admin ? admin_url('edit.php?post_type=product&page=dsmart-shop-analytics') : get_permalink();
$export = wp_nonce_url(add_query_arg(array_merge($f, array('action' => 'dsmart_analytics_export')), admin_url('admin-post.php')), 'dsmart_analytics_export');
$money = function ($value) { return number_format((float) $value, 2, ',', '.') . ' €'; };
$weekdays = array(__('Montag', 'dsmart'), __('Dienstag', 'dsmart'), __('Mittwoch', 'dsmart'), __('Donnerstag', 'dsmart'), __('Freitag', 'dsmart'), __('Samstag', 'dsmart'), __('Sonntag', 'dsmart'));
?>
<link rel="stylesheet" href="<?php echo esc_url(plugins_url('../css/shop-analytics.css', __FILE__)); ?>">
<section class="ds-analytics" lang="de">
    <div class="ds-analytics-heading"><div><h2><?php esc_html_e('Statistik & Analyse', 'dsmart'); ?></h2><p><?php esc_html_e('Produkte auswerten und die beliebtesten Bestellzeiten erkennen.', 'dsmart'); ?></p></div><a class="dsmart-button" href="<?php echo esc_url($export); ?>"><?php esc_html_e('Als Excel exportieren', 'dsmart'); ?></a></div>
    <form method="get" action="<?php echo esc_url($analytics_url); ?>" class="ds-analytics-filters">
        <input type="hidden" name="section" value="statistics">
        <?php if ($analytics_admin) : ?><input type="hidden" name="post_type" value="product"><input type="hidden" name="page" value="dsmart-shop-analytics"><?php endif; ?>
        <?php if (!$analytics_admin && !get_option('permalink_structure')) : ?><input type="hidden" name="page_id" value="<?php echo esc_attr(get_queried_object_id()); ?>"><?php endif; ?>
        <label><?php esc_html_e('Zeitraum', 'dsmart'); ?><select name="period" id="ds-period">
        <?php foreach (array('1' => __('Heute', 'dsmart'), 'yesterday' => __('Gestern', 'dsmart'), '7' => __('Letzte 7 Tage', 'dsmart'), '30' => __('Letzte 30 Tage', 'dsmart'), '365' => __('Letzte 365 Tage', 'dsmart'), 'year' => __('Letztes Kalenderjahr', 'dsmart'), 'custom' => __('Eigener Zeitraum', 'dsmart')) as $value => $label) : ?><option value="<?php echo esc_attr($value); ?>" <?php selected($f['period'], $value); ?>><?php echo esc_html($label); ?></option><?php endforeach; ?></select></label>
        <label><?php esc_html_e('Von', 'dsmart'); ?><input type="date" name="from" value="<?php echo esc_attr($f['from']); ?>" required></label>
        <label><?php esc_html_e('Bis', 'dsmart'); ?><input type="date" name="to" value="<?php echo esc_attr($f['to']); ?>" required></label>
        <?php foreach (array('method' => array(__('Bestellart', 'dsmart'), array('all' => __('Alle Bestellarten', 'dsmart'), 'shipping' => __('Lieferung', 'dsmart'), 'direct' => __('Abholung', 'dsmart'))), 'status' => array(__('Bestellstatus', 'dsmart'), array('completed' => __('Abgeschlossen', 'dsmart'), 'processing' => __('In Bearbeitung', 'dsmart'), 'cancelled' => __('Storniert', 'dsmart'), 'all' => __('Alle Status', 'dsmart'))), 'sort' => array(__('Produkte sortieren nach', 'dsmart'), array('name' => __('Name', 'dsmart'), 'quantity' => __('Menge', 'dsmart'), 'orders' => __('Beliebtheit / Bestellungen', 'dsmart'), 'revenue' => __('Produktumsatz', 'dsmart'), 'shipping' => __('Liefermenge', 'dsmart'), 'direct' => __('Abholmenge', 'dsmart'), 'last' => __('Zuletzt bestellt', 'dsmart'))), 'direction' => array(__('Sortierreihenfolge', 'dsmart'), array('desc' => __('Absteigend', 'dsmart'), 'asc' => __('Aufsteigend', 'dsmart')))) as $key => $control) : ?>
        <label><?php echo esc_html($control[0]); ?><select name="<?php echo esc_attr($key); ?>"><?php foreach ($control[1] as $value => $label) : ?><option value="<?php echo esc_attr($value); ?>" <?php selected($f[$key], $value); ?>><?php echo esc_html($label); ?></option><?php endforeach; ?></select></label>
        <?php endforeach; ?>
        <label><?php esc_html_e('Produkte suchen', 'dsmart'); ?><input type="search" name="search" value="<?php echo esc_attr($f['search']); ?>"></label>
        <button class="dsmart-button" type="submit"><?php esc_html_e('Filter anwenden', 'dsmart'); ?></button><a href="<?php echo esc_url(add_query_arg('section', 'statistics', $analytics_url)); ?>"><?php esc_html_e('Zurücksetzen', 'dsmart'); ?></a>
    </form>
    <p class="ds-analytics-note"><?php echo esc_html((new DateTimeImmutable($f['from']))->format('d.m.Y') . ' – ' . (new DateTimeImmutable($f['to']))->format('d.m.Y') . ' · ' . wp_timezone_string()); ?>. <?php esc_html_e('Start- und Enddatum sind eingeschlossen. Maßgeblich ist der Bestellzeitpunkt. Die Produktsuche filtert nur die Produkttabelle und deren Export. Gesamtwerte berücksichtigen alle Bestellungen im gewählten Zeitraum mit passendem Status und passender Bestellart.', 'dsmart'); ?></p>
    <div class="ds-analytics-cards">
    <?php foreach (array(__('Bestellungen', 'dsmart') => $r['orders'], __('Bestellte Artikel', 'dsmart') => $r['quantity'], __('Bestellumsatz', 'dsmart') => $money($r['revenue']), __('Durchschnittlicher Bestellwert', 'dsmart') => $money($r['orders'] ? $r['revenue'] / $r['orders'] : 0)) as $label => $value) : ?><article><span><?php echo esc_html($label); ?></span><strong><?php echo esc_html($value); ?></strong></article><?php endforeach; ?>
    </div>
    <?php if (!$r['orders']) : ?><p role="status"><?php esc_html_e('Keine Bestellungen für diese Filter gefunden. Bitte einen anderen Zeitraum oder Status auswählen.', 'dsmart'); ?></p><?php endif; ?>
    <div class="ds-analytics-tabs" role="tablist" aria-label="<?php esc_attr_e('Berichtsansichten', 'dsmart'); ?>"><button type="button" role="tab" id="ds-products-tab" aria-controls="ds-products" aria-selected="true"><?php esc_html_e('Produkte', 'dsmart'); ?></button><button type="button" role="tab" id="ds-time-tab" aria-controls="ds-time" aria-selected="false" tabindex="-1"><?php esc_html_e('Uhrzeit & Wochentag', 'dsmart'); ?></button></div>
    <div id="ds-products" role="tabpanel" aria-labelledby="ds-products-tab">
        <h3><?php esc_html_e('Produktauswertung', 'dsmart'); ?></h3>
        <p><?php esc_html_e('Beliebtheit bezeichnet den Anteil der ausgewählten Bestellungen, die ein Produkt enthalten. Varianten werden zusammengefasst. Der Produktumsatz enthält die gespeicherten Positionsbeträge einschließlich Extras, vor Bestellrabatten und Liefergebühren. Alle Beträge werden in Euro angezeigt.', 'dsmart'); ?></p>
        <div class="ds-analytics-scroll"><table><thead><tr><?php foreach (array(__('Produkt', 'dsmart'), __('Menge', 'dsmart'), __('Bestellungen', 'dsmart'), __('Beliebtheit', 'dsmart'), __('Produktumsatz', 'dsmart'), __('Liefermenge', 'dsmart'), __('Abholmenge', 'dsmart'), __('Sonstige Menge', 'dsmart'), __('Zuletzt bestellt', 'dsmart')) as $label) { echo '<th scope="col">' . esc_html($label) . '</th>'; } ?></tr></thead><tbody>
        <?php $page = isset($_GET['product_page']) && is_scalar($_GET['product_page']) ? max(1, absint($_GET['product_page'])) : 1; $pages = max(1, (int) ceil(count($r['products']) / 25)); $page = min($page, $pages);
        foreach (array_slice($r['products'], ($page - 1) * 25, 25) as $p) : ?><tr><th scope="row"><?php echo esc_html($p['name']); ?></th><td><?php echo esc_html($p['quantity']); ?></td><td><?php echo esc_html($p['orders']); ?></td><td><?php $pop = $r['orders'] ? round(100 * $p['orders'] / $r['orders'], 1) : 0; echo esc_html(number_format($pop, 1, ',', '.') . ' %'); ?><meter min="0" max="100" value="<?php echo esc_attr($pop); ?>" aria-label="<?php esc_attr_e('Beliebtheit', 'dsmart'); ?>"></meter></td><td><?php echo esc_html($money($p['revenue'])); ?></td><td><?php echo esc_html($p['shipping']); ?></td><td><?php echo esc_html($p['direct']); ?></td><td><?php echo esc_html($p['unknown']); ?></td><td><?php echo esc_html((new DateTimeImmutable($p['last']))->format('d.m.Y H:i')); ?></td></tr><?php endforeach; ?>
        <?php if (!$r['products']) : ?><tr><td colspan="9"><?php esc_html_e('Keine Produkte für diese Filter gefunden.', 'dsmart'); ?></td></tr><?php endif; ?>
        </tbody></table></div>
        <nav class="ds-analytics-pagination" aria-label="<?php esc_attr_e('Produktseiten', 'dsmart'); ?>"><?php echo esc_html(sprintf(__('Seite %1$d von %2$d · %3$d Produkte', 'dsmart'), $page, $pages, count($r['products']))); ?> <?php foreach (array($page - 1 => __('Zurück', 'dsmart'), $page + 1 => __('Weiter', 'dsmart')) as $target => $label) { if ($target >= 1 && $target <= $pages) { echo '<a href="' . esc_url(add_query_arg(array_merge($f, array('section' => 'statistics', 'product_page' => $target)), $analytics_url)) . '">' . esc_html($label) . '</a>'; } } ?></nav>
    </div>
    <div id="ds-time" role="tabpanel" aria-labelledby="ds-time-tab" hidden>
        <h3><?php esc_html_e('Wann Kunden bestellen', 'dsmart'); ?></h3>
        <?php if ($r['orders']) : ?><p><?php echo esc_html(sprintf(__('Stärkster Wochentag: %1$s · Stärkste Stunde: %2$s · Lieferung: %3$d · Abholung: %4$d · Sonstige: %5$d Bestellungen. Bei Gleichstand wird der erste Zeitraum angezeigt.', 'dsmart'), $weekdays[array_search(max($r['weekdays']), $r['weekdays'], true)], sprintf('%02d:00–%02d:59', array_search(max($r['hours']), $r['hours'], true), array_search(max($r['hours']), $r['hours'], true)), $r['methods']['shipping'], $r['methods']['direct'], $r['methods']['unknown'])); ?></p><?php endif; ?>
        <h4><?php esc_html_e('Bestellungen nach Wochentag und Uhrzeit', 'dsmart'); ?></h4><div class="ds-analytics-scroll"><table class="ds-heatmap"><thead><tr><th scope="col"><?php esc_html_e('Tag / Stunde', 'dsmart'); ?></th><?php for ($hour = 0; $hour < 24; $hour++) { echo '<th scope="col">' . esc_html(sprintf('%02d', $hour)) . '</th>'; } ?></tr></thead><tbody>
        <?php $peak = max(1, max(array_map('max', $r['heatmap']))); foreach ($weekdays as $day => $name) : ?><tr><th scope="row"><?php echo esc_html($name); ?></th><?php foreach ($r['heatmap'][$day] as $hour => $count) : ?><td style="background:rgba(37,99,235,<?php echo esc_attr(round(.06 + .35 * $count / $peak, 2)); ?>)" title="<?php echo esc_attr($name . ' ' . sprintf('%02d:00', $hour) . ': ' . $count); ?>"><?php echo esc_html($count); ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div>
        <div class="ds-analytics-charts"><?php foreach (array(__('Bestellungen nach Wochentag', 'dsmart') => $r['weekdays'], __('Bestellungen nach Uhrzeit', 'dsmart') => $r['hours']) as $title => $values) : ?><article><h4><?php echo esc_html($title); ?></h4><?php foreach ($values as $key => $count) : ?><div class="ds-analytics-bar"><span><?php echo esc_html(count($values) === 7 ? $weekdays[$key] : sprintf('%02d:00', $key)); ?></span><meter min="0" max="<?php echo esc_attr(max(1, max($values))); ?>" value="<?php echo esc_attr($count); ?>" aria-label="<?php echo esc_attr($title); ?>"></meter><b><?php echo esc_html($count); ?></b></div><?php endforeach; ?></article><?php endforeach; ?></div>
        <h4><?php esc_html_e('Tagesübersicht', 'dsmart'); ?></h4><p><?php esc_html_e('Tage ohne Bestellungen werden nicht angezeigt. Alle passenden Bestelltage sind im Excel-Export enthalten.', 'dsmart'); ?></p><div class="ds-analytics-scroll ds-daily"><table><thead><tr><?php foreach (array(__('Datum', 'dsmart'), __('Bestellungen', 'dsmart'), __('Bestellumsatz', 'dsmart'), __('Lieferung', 'dsmart'), __('Abholung', 'dsmart'), __('Sonstige', 'dsmart')) as $label) { echo '<th scope="col">' . esc_html($label) . '</th>'; } ?></tr></thead><tbody><?php foreach ($r['days'] as $day => $values) { echo '<tr><th scope="row">' . esc_html((new DateTimeImmutable($day))->format('d.m.Y')) . '</th>'; foreach ($values as $key => $value) { echo '<td>' . esc_html($key === 'revenue' ? $money($value) : $value) . '</td>'; } echo '</tr>'; } ?></tbody></table></div>
    </div>
</section>
<script src="<?php echo esc_url(plugins_url('../js/shop-analytics.js', __FILE__)); ?>" defer></script>
